// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// GetAllMetricsReader is a Reader for the GetAllMetrics structure.
type GetAllMetricsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllMetricsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllMetricsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllMetricsOK creates a GetAllMetricsOK with default headers values
func NewGetAllMetricsOK() *GetAllMetricsOK {
	return &GetAllMetricsOK{}
}

/* GetAllMetricsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllMetricsOK struct {
	Payload *models.Metrics
}

func (o *GetAllMetricsOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/server/metrics][%d] getAllMetricsOK  %+v", 200, o.Payload)
}
func (o *GetAllMetricsOK) GetPayload() *models.Metrics {
	return o.Payload
}

func (o *GetAllMetricsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Metrics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
