// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddParameterToBuildStepParams creates a new AddParameterToBuildStepParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddParameterToBuildStepParams() *AddParameterToBuildStepParams {
	return &AddParameterToBuildStepParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddParameterToBuildStepParamsWithTimeout creates a new AddParameterToBuildStepParams object
// with the ability to set a timeout on a request.
func NewAddParameterToBuildStepParamsWithTimeout(timeout time.Duration) *AddParameterToBuildStepParams {
	return &AddParameterToBuildStepParams{
		timeout: timeout,
	}
}

// NewAddParameterToBuildStepParamsWithContext creates a new AddParameterToBuildStepParams object
// with the ability to set a context for a request.
func NewAddParameterToBuildStepParamsWithContext(ctx context.Context) *AddParameterToBuildStepParams {
	return &AddParameterToBuildStepParams{
		Context: ctx,
	}
}

// NewAddParameterToBuildStepParamsWithHTTPClient creates a new AddParameterToBuildStepParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddParameterToBuildStepParamsWithHTTPClient(client *http.Client) *AddParameterToBuildStepParams {
	return &AddParameterToBuildStepParams{
		HTTPClient: client,
	}
}

/* AddParameterToBuildStepParams contains all the parameters to send to the API endpoint
   for the add parameter to build step operation.

   Typically these are written to a http.Request.
*/
type AddParameterToBuildStepParams struct {

	// Body.
	Body string

	// BtLocator.
	//
	// Format: BuildTypeLocator
	BtLocator string

	// ParameterName.
	ParameterName string

	// StepID.
	StepID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add parameter to build step params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddParameterToBuildStepParams) WithDefaults() *AddParameterToBuildStepParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add parameter to build step params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddParameterToBuildStepParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithTimeout(timeout time.Duration) *AddParameterToBuildStepParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithContext(ctx context.Context) *AddParameterToBuildStepParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithHTTPClient(client *http.Client) *AddParameterToBuildStepParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithBody(body string) *AddParameterToBuildStepParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetBody(body string) {
	o.Body = body
}

// WithBtLocator adds the btLocator to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithBtLocator(btLocator string) *AddParameterToBuildStepParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithParameterName adds the parameterName to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithParameterName(parameterName string) *AddParameterToBuildStepParams {
	o.SetParameterName(parameterName)
	return o
}

// SetParameterName adds the parameterName to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetParameterName(parameterName string) {
	o.ParameterName = parameterName
}

// WithStepID adds the stepID to the add parameter to build step params
func (o *AddParameterToBuildStepParams) WithStepID(stepID string) *AddParameterToBuildStepParams {
	o.SetStepID(stepID)
	return o
}

// SetStepID adds the stepId to the add parameter to build step params
func (o *AddParameterToBuildStepParams) SetStepID(stepID string) {
	o.StepID = stepID
}

// WriteToRequest writes these params to a swagger request
func (o *AddParameterToBuildStepParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	// path param parameterName
	if err := r.SetPathParam("parameterName", o.ParameterName); err != nil {
		return err
	}

	// path param stepId
	if err := r.SetPathParam("stepId", o.StepID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
