// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllAgentRequirementsParams creates a new GetAllAgentRequirementsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllAgentRequirementsParams() *GetAllAgentRequirementsParams {
	return &GetAllAgentRequirementsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllAgentRequirementsParamsWithTimeout creates a new GetAllAgentRequirementsParams object
// with the ability to set a timeout on a request.
func NewGetAllAgentRequirementsParamsWithTimeout(timeout time.Duration) *GetAllAgentRequirementsParams {
	return &GetAllAgentRequirementsParams{
		timeout: timeout,
	}
}

// NewGetAllAgentRequirementsParamsWithContext creates a new GetAllAgentRequirementsParams object
// with the ability to set a context for a request.
func NewGetAllAgentRequirementsParamsWithContext(ctx context.Context) *GetAllAgentRequirementsParams {
	return &GetAllAgentRequirementsParams{
		Context: ctx,
	}
}

// NewGetAllAgentRequirementsParamsWithHTTPClient creates a new GetAllAgentRequirementsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllAgentRequirementsParamsWithHTTPClient(client *http.Client) *GetAllAgentRequirementsParams {
	return &GetAllAgentRequirementsParams{
		HTTPClient: client,
	}
}

/* GetAllAgentRequirementsParams contains all the parameters to send to the API endpoint
   for the get all agent requirements operation.

   Typically these are written to a http.Request.
*/
type GetAllAgentRequirementsParams struct {

	// BtLocator.
	//
	// Format: BuildTypeLocator
	BtLocator string

	// Fields.
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all agent requirements params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllAgentRequirementsParams) WithDefaults() *GetAllAgentRequirementsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all agent requirements params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllAgentRequirementsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) WithTimeout(timeout time.Duration) *GetAllAgentRequirementsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) WithContext(ctx context.Context) *GetAllAgentRequirementsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) WithHTTPClient(client *http.Client) *GetAllAgentRequirementsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBtLocator adds the btLocator to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) WithBtLocator(btLocator string) *GetAllAgentRequirementsParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithFields adds the fields to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) WithFields(fields *string) *GetAllAgentRequirementsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get all agent requirements params
func (o *GetAllAgentRequirementsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAgentRequirementsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
