// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// GetAllArtifactDependenciesReader is a Reader for the GetAllArtifactDependencies structure.
type GetAllArtifactDependenciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllArtifactDependenciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllArtifactDependenciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllArtifactDependenciesOK creates a GetAllArtifactDependenciesOK with default headers values
func NewGetAllArtifactDependenciesOK() *GetAllArtifactDependenciesOK {
	return &GetAllArtifactDependenciesOK{}
}

/* GetAllArtifactDependenciesOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllArtifactDependenciesOK struct {
	Payload *models.ArtifactDependencies
}

func (o *GetAllArtifactDependenciesOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/buildTypes/{btLocator}/artifact-dependencies][%d] getAllArtifactDependenciesOK  %+v", 200, o.Payload)
}
func (o *GetAllArtifactDependenciesOK) GetPayload() *models.ArtifactDependencies {
	return o.Payload
}

func (o *GetAllArtifactDependenciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ArtifactDependencies)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
