// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetArtifactDependencyParams creates a new GetArtifactDependencyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetArtifactDependencyParams() *GetArtifactDependencyParams {
	return &GetArtifactDependencyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetArtifactDependencyParamsWithTimeout creates a new GetArtifactDependencyParams object
// with the ability to set a timeout on a request.
func NewGetArtifactDependencyParamsWithTimeout(timeout time.Duration) *GetArtifactDependencyParams {
	return &GetArtifactDependencyParams{
		timeout: timeout,
	}
}

// NewGetArtifactDependencyParamsWithContext creates a new GetArtifactDependencyParams object
// with the ability to set a context for a request.
func NewGetArtifactDependencyParamsWithContext(ctx context.Context) *GetArtifactDependencyParams {
	return &GetArtifactDependencyParams{
		Context: ctx,
	}
}

// NewGetArtifactDependencyParamsWithHTTPClient creates a new GetArtifactDependencyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetArtifactDependencyParamsWithHTTPClient(client *http.Client) *GetArtifactDependencyParams {
	return &GetArtifactDependencyParams{
		HTTPClient: client,
	}
}

/* GetArtifactDependencyParams contains all the parameters to send to the API endpoint
   for the get artifact dependency operation.

   Typically these are written to a http.Request.
*/
type GetArtifactDependencyParams struct {

	// ArtifactDepLocator.
	ArtifactDepLocator string

	// BtLocator.
	//
	// Format: BuildTypeLocator
	BtLocator string

	// Fields.
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get artifact dependency params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetArtifactDependencyParams) WithDefaults() *GetArtifactDependencyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get artifact dependency params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetArtifactDependencyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get artifact dependency params
func (o *GetArtifactDependencyParams) WithTimeout(timeout time.Duration) *GetArtifactDependencyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get artifact dependency params
func (o *GetArtifactDependencyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get artifact dependency params
func (o *GetArtifactDependencyParams) WithContext(ctx context.Context) *GetArtifactDependencyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get artifact dependency params
func (o *GetArtifactDependencyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get artifact dependency params
func (o *GetArtifactDependencyParams) WithHTTPClient(client *http.Client) *GetArtifactDependencyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get artifact dependency params
func (o *GetArtifactDependencyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArtifactDepLocator adds the artifactDepLocator to the get artifact dependency params
func (o *GetArtifactDependencyParams) WithArtifactDepLocator(artifactDepLocator string) *GetArtifactDependencyParams {
	o.SetArtifactDepLocator(artifactDepLocator)
	return o
}

// SetArtifactDepLocator adds the artifactDepLocator to the get artifact dependency params
func (o *GetArtifactDependencyParams) SetArtifactDepLocator(artifactDepLocator string) {
	o.ArtifactDepLocator = artifactDepLocator
}

// WithBtLocator adds the btLocator to the get artifact dependency params
func (o *GetArtifactDependencyParams) WithBtLocator(btLocator string) *GetArtifactDependencyParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the get artifact dependency params
func (o *GetArtifactDependencyParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithFields adds the fields to the get artifact dependency params
func (o *GetArtifactDependencyParams) WithFields(fields *string) *GetArtifactDependencyParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get artifact dependency params
func (o *GetArtifactDependencyParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetArtifactDependencyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param artifactDepLocator
	if err := r.SetPathParam("artifactDepLocator", o.ArtifactDepLocator); err != nil {
		return err
	}

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
