// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewReplaceAllArtifactDependenciesParams creates a new ReplaceAllArtifactDependenciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceAllArtifactDependenciesParams() *ReplaceAllArtifactDependenciesParams {
	return &ReplaceAllArtifactDependenciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceAllArtifactDependenciesParamsWithTimeout creates a new ReplaceAllArtifactDependenciesParams object
// with the ability to set a timeout on a request.
func NewReplaceAllArtifactDependenciesParamsWithTimeout(timeout time.Duration) *ReplaceAllArtifactDependenciesParams {
	return &ReplaceAllArtifactDependenciesParams{
		timeout: timeout,
	}
}

// NewReplaceAllArtifactDependenciesParamsWithContext creates a new ReplaceAllArtifactDependenciesParams object
// with the ability to set a context for a request.
func NewReplaceAllArtifactDependenciesParamsWithContext(ctx context.Context) *ReplaceAllArtifactDependenciesParams {
	return &ReplaceAllArtifactDependenciesParams{
		Context: ctx,
	}
}

// NewReplaceAllArtifactDependenciesParamsWithHTTPClient creates a new ReplaceAllArtifactDependenciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceAllArtifactDependenciesParamsWithHTTPClient(client *http.Client) *ReplaceAllArtifactDependenciesParams {
	return &ReplaceAllArtifactDependenciesParams{
		HTTPClient: client,
	}
}

/* ReplaceAllArtifactDependenciesParams contains all the parameters to send to the API endpoint
   for the replace all artifact dependencies operation.

   Typically these are written to a http.Request.
*/
type ReplaceAllArtifactDependenciesParams struct {

	// Body.
	Body *models.ArtifactDependencies

	// BtLocator.
	//
	// Format: BuildTypeLocator
	BtLocator string

	// Fields.
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace all artifact dependencies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceAllArtifactDependenciesParams) WithDefaults() *ReplaceAllArtifactDependenciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace all artifact dependencies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceAllArtifactDependenciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) WithTimeout(timeout time.Duration) *ReplaceAllArtifactDependenciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) WithContext(ctx context.Context) *ReplaceAllArtifactDependenciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) WithHTTPClient(client *http.Client) *ReplaceAllArtifactDependenciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) WithBody(body *models.ArtifactDependencies) *ReplaceAllArtifactDependenciesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) SetBody(body *models.ArtifactDependencies) {
	o.Body = body
}

// WithBtLocator adds the btLocator to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) WithBtLocator(btLocator string) *ReplaceAllArtifactDependenciesParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithFields adds the fields to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) WithFields(fields *string) *ReplaceAllArtifactDependenciesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the replace all artifact dependencies params
func (o *ReplaceAllArtifactDependenciesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceAllArtifactDependenciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
