// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewReplaceSnapshotDependencyParams creates a new ReplaceSnapshotDependencyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceSnapshotDependencyParams() *ReplaceSnapshotDependencyParams {
	return &ReplaceSnapshotDependencyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceSnapshotDependencyParamsWithTimeout creates a new ReplaceSnapshotDependencyParams object
// with the ability to set a timeout on a request.
func NewReplaceSnapshotDependencyParamsWithTimeout(timeout time.Duration) *ReplaceSnapshotDependencyParams {
	return &ReplaceSnapshotDependencyParams{
		timeout: timeout,
	}
}

// NewReplaceSnapshotDependencyParamsWithContext creates a new ReplaceSnapshotDependencyParams object
// with the ability to set a context for a request.
func NewReplaceSnapshotDependencyParamsWithContext(ctx context.Context) *ReplaceSnapshotDependencyParams {
	return &ReplaceSnapshotDependencyParams{
		Context: ctx,
	}
}

// NewReplaceSnapshotDependencyParamsWithHTTPClient creates a new ReplaceSnapshotDependencyParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceSnapshotDependencyParamsWithHTTPClient(client *http.Client) *ReplaceSnapshotDependencyParams {
	return &ReplaceSnapshotDependencyParams{
		HTTPClient: client,
	}
}

/* ReplaceSnapshotDependencyParams contains all the parameters to send to the API endpoint
   for the replace snapshot dependency operation.

   Typically these are written to a http.Request.
*/
type ReplaceSnapshotDependencyParams struct {

	// Body.
	Body *models.SnapshotDependency

	// BtLocator.
	//
	// Format: BuildTypeLocator
	BtLocator string

	// Fields.
	Fields *string

	// SnapshotDepLocator.
	SnapshotDepLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace snapshot dependency params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceSnapshotDependencyParams) WithDefaults() *ReplaceSnapshotDependencyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace snapshot dependency params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceSnapshotDependencyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithTimeout(timeout time.Duration) *ReplaceSnapshotDependencyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithContext(ctx context.Context) *ReplaceSnapshotDependencyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithHTTPClient(client *http.Client) *ReplaceSnapshotDependencyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithBody(body *models.SnapshotDependency) *ReplaceSnapshotDependencyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetBody(body *models.SnapshotDependency) {
	o.Body = body
}

// WithBtLocator adds the btLocator to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithBtLocator(btLocator string) *ReplaceSnapshotDependencyParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithFields adds the fields to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithFields(fields *string) *ReplaceSnapshotDependencyParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithSnapshotDepLocator adds the snapshotDepLocator to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) WithSnapshotDepLocator(snapshotDepLocator string) *ReplaceSnapshotDependencyParams {
	o.SetSnapshotDepLocator(snapshotDepLocator)
	return o
}

// SetSnapshotDepLocator adds the snapshotDepLocator to the replace snapshot dependency params
func (o *ReplaceSnapshotDependencyParams) SetSnapshotDepLocator(snapshotDepLocator string) {
	o.SnapshotDepLocator = snapshotDepLocator
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceSnapshotDependencyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param snapshotDepLocator
	if err := r.SetPathParam("snapshotDepLocator", o.SnapshotDepLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
