// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewReplaceBuildStepParams creates a new ReplaceBuildStepParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceBuildStepParams() *ReplaceBuildStepParams {
	return &ReplaceBuildStepParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceBuildStepParamsWithTimeout creates a new ReplaceBuildStepParams object
// with the ability to set a timeout on a request.
func NewReplaceBuildStepParamsWithTimeout(timeout time.Duration) *ReplaceBuildStepParams {
	return &ReplaceBuildStepParams{
		timeout: timeout,
	}
}

// NewReplaceBuildStepParamsWithContext creates a new ReplaceBuildStepParams object
// with the ability to set a context for a request.
func NewReplaceBuildStepParamsWithContext(ctx context.Context) *ReplaceBuildStepParams {
	return &ReplaceBuildStepParams{
		Context: ctx,
	}
}

// NewReplaceBuildStepParamsWithHTTPClient creates a new ReplaceBuildStepParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceBuildStepParamsWithHTTPClient(client *http.Client) *ReplaceBuildStepParams {
	return &ReplaceBuildStepParams{
		HTTPClient: client,
	}
}

/* ReplaceBuildStepParams contains all the parameters to send to the API endpoint
   for the replace build step operation.

   Typically these are written to a http.Request.
*/
type ReplaceBuildStepParams struct {

	// Body.
	Body *models.Step

	// BtLocator.
	//
	// Format: BuildTypeLocator
	BtLocator string

	// Fields.
	Fields *string

	// StepID.
	StepID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace build step params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceBuildStepParams) WithDefaults() *ReplaceBuildStepParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace build step params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceBuildStepParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the replace build step params
func (o *ReplaceBuildStepParams) WithTimeout(timeout time.Duration) *ReplaceBuildStepParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace build step params
func (o *ReplaceBuildStepParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace build step params
func (o *ReplaceBuildStepParams) WithContext(ctx context.Context) *ReplaceBuildStepParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace build step params
func (o *ReplaceBuildStepParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace build step params
func (o *ReplaceBuildStepParams) WithHTTPClient(client *http.Client) *ReplaceBuildStepParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace build step params
func (o *ReplaceBuildStepParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace build step params
func (o *ReplaceBuildStepParams) WithBody(body *models.Step) *ReplaceBuildStepParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace build step params
func (o *ReplaceBuildStepParams) SetBody(body *models.Step) {
	o.Body = body
}

// WithBtLocator adds the btLocator to the replace build step params
func (o *ReplaceBuildStepParams) WithBtLocator(btLocator string) *ReplaceBuildStepParams {
	o.SetBtLocator(btLocator)
	return o
}

// SetBtLocator adds the btLocator to the replace build step params
func (o *ReplaceBuildStepParams) SetBtLocator(btLocator string) {
	o.BtLocator = btLocator
}

// WithFields adds the fields to the replace build step params
func (o *ReplaceBuildStepParams) WithFields(fields *string) *ReplaceBuildStepParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the replace build step params
func (o *ReplaceBuildStepParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithStepID adds the stepID to the replace build step params
func (o *ReplaceBuildStepParams) WithStepID(stepID string) *ReplaceBuildStepParams {
	o.SetStepID(stepID)
	return o
}

// SetStepID adds the stepId to the replace build step params
func (o *ReplaceBuildStepParams) SetStepID(stepID string) {
	o.StepID = stepID
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceBuildStepParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param btLocator
	if err := r.SetPathParam("btLocator", o.BtLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param stepId
	if err := r.SetPathParam("stepId", o.StepID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
