// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetTriggerParameterReader is a Reader for the SetTriggerParameter structure.
type SetTriggerParameterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetTriggerParameterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetTriggerParameterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetTriggerParameterOK creates a SetTriggerParameterOK with default headers values
func NewSetTriggerParameterOK() *SetTriggerParameterOK {
	return &SetTriggerParameterOK{}
}

/* SetTriggerParameterOK describes a response with status code 200, with default header values.

successful operation
*/
type SetTriggerParameterOK struct {
	Payload string
}

func (o *SetTriggerParameterOK) Error() string {
	return fmt.Sprintf("[PUT /app/rest/buildTypes/{btLocator}/triggers/{triggerLocator}/{fieldName}][%d] setTriggerParameterOK  %+v", 200, o.Payload)
}
func (o *SetTriggerParameterOK) GetPayload() string {
	return o.Payload
}

func (o *SetTriggerParameterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
