// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// UpdateBuildParameterOfBuildTypeReader is a Reader for the UpdateBuildParameterOfBuildType structure.
type UpdateBuildParameterOfBuildTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBuildParameterOfBuildTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBuildParameterOfBuildTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateBuildParameterOfBuildTypeOK creates a UpdateBuildParameterOfBuildTypeOK with default headers values
func NewUpdateBuildParameterOfBuildTypeOK() *UpdateBuildParameterOfBuildTypeOK {
	return &UpdateBuildParameterOfBuildTypeOK{}
}

/* UpdateBuildParameterOfBuildTypeOK describes a response with status code 200, with default header values.

successful operation
*/
type UpdateBuildParameterOfBuildTypeOK struct {
	Payload *models.Property
}

func (o *UpdateBuildParameterOfBuildTypeOK) Error() string {
	return fmt.Sprintf("[PUT /app/rest/buildTypes/{btLocator}/parameters/{name}][%d] updateBuildParameterOfBuildTypeOK  %+v", 200, o.Payload)
}
func (o *UpdateBuildParameterOfBuildTypeOK) GetPayload() *models.Property {
	return o.Payload
}

func (o *UpdateBuildParameterOfBuildTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Property)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
