// Code generated by go-swagger; DO NOT EDIT.

package build_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateBuildTypeVcsRootCheckoutRulesReader is a Reader for the UpdateBuildTypeVcsRootCheckoutRules structure.
type UpdateBuildTypeVcsRootCheckoutRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBuildTypeVcsRootCheckoutRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBuildTypeVcsRootCheckoutRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateBuildTypeVcsRootCheckoutRulesOK creates a UpdateBuildTypeVcsRootCheckoutRulesOK with default headers values
func NewUpdateBuildTypeVcsRootCheckoutRulesOK() *UpdateBuildTypeVcsRootCheckoutRulesOK {
	return &UpdateBuildTypeVcsRootCheckoutRulesOK{}
}

/* UpdateBuildTypeVcsRootCheckoutRulesOK describes a response with status code 200, with default header values.

successful operation
*/
type UpdateBuildTypeVcsRootCheckoutRulesOK struct {
	Payload string
}

func (o *UpdateBuildTypeVcsRootCheckoutRulesOK) Error() string {
	return fmt.Sprintf("[PUT /app/rest/buildTypes/{btLocator}/vcs-root-entries/{vcsRootLocator}/checkout-rules][%d] updateBuildTypeVcsRootCheckoutRulesOK  %+v", 200, o.Payload)
}
func (o *UpdateBuildTypeVcsRootCheckoutRulesOK) GetPayload() string {
	return o.Payload
}

func (o *UpdateBuildTypeVcsRootCheckoutRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
