// Code generated by go-swagger; DO NOT EDIT.

package problem_occurrence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// GetAllBuildProblemOccurrencesReader is a Reader for the GetAllBuildProblemOccurrences structure.
type GetAllBuildProblemOccurrencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllBuildProblemOccurrencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllBuildProblemOccurrencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllBuildProblemOccurrencesOK creates a GetAllBuildProblemOccurrencesOK with default headers values
func NewGetAllBuildProblemOccurrencesOK() *GetAllBuildProblemOccurrencesOK {
	return &GetAllBuildProblemOccurrencesOK{}
}

/* GetAllBuildProblemOccurrencesOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllBuildProblemOccurrencesOK struct {
	Payload *models.ProblemOccurrences
}

func (o *GetAllBuildProblemOccurrencesOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/problemOccurrences][%d] getAllBuildProblemOccurrencesOK  %+v", 200, o.Payload)
}
func (o *GetAllBuildProblemOccurrencesOK) GetPayload() *models.ProblemOccurrences {
	return o.Payload
}

func (o *GetAllBuildProblemOccurrencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemOccurrences)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
