// Code generated by go-swagger; DO NOT EDIT.

package agent_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAllProjectsFromAgentPoolReader is a Reader for the DeleteAllProjectsFromAgentPool structure.
type DeleteAllProjectsFromAgentPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAllProjectsFromAgentPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteAllProjectsFromAgentPoolDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteAllProjectsFromAgentPoolDefault creates a DeleteAllProjectsFromAgentPoolDefault with default headers values
func NewDeleteAllProjectsFromAgentPoolDefault(code int) *DeleteAllProjectsFromAgentPoolDefault {
	return &DeleteAllProjectsFromAgentPoolDefault{
		_statusCode: code,
	}
}

/* DeleteAllProjectsFromAgentPoolDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteAllProjectsFromAgentPoolDefault struct {
	_statusCode int
}

// Code gets the status code for the delete all projects from agent pool default response
func (o *DeleteAllProjectsFromAgentPoolDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAllProjectsFromAgentPoolDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/agentPools/{agentPoolLocator}/projects][%d] deleteAllProjectsFromAgentPool default ", o._statusCode)
}

func (o *DeleteAllProjectsFromAgentPoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
