// Code generated by go-swagger; DO NOT EDIT.

package agent_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllAgentsFromAgentPoolParams creates a new GetAllAgentsFromAgentPoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllAgentsFromAgentPoolParams() *GetAllAgentsFromAgentPoolParams {
	return &GetAllAgentsFromAgentPoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllAgentsFromAgentPoolParamsWithTimeout creates a new GetAllAgentsFromAgentPoolParams object
// with the ability to set a timeout on a request.
func NewGetAllAgentsFromAgentPoolParamsWithTimeout(timeout time.Duration) *GetAllAgentsFromAgentPoolParams {
	return &GetAllAgentsFromAgentPoolParams{
		timeout: timeout,
	}
}

// NewGetAllAgentsFromAgentPoolParamsWithContext creates a new GetAllAgentsFromAgentPoolParams object
// with the ability to set a context for a request.
func NewGetAllAgentsFromAgentPoolParamsWithContext(ctx context.Context) *GetAllAgentsFromAgentPoolParams {
	return &GetAllAgentsFromAgentPoolParams{
		Context: ctx,
	}
}

// NewGetAllAgentsFromAgentPoolParamsWithHTTPClient creates a new GetAllAgentsFromAgentPoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllAgentsFromAgentPoolParamsWithHTTPClient(client *http.Client) *GetAllAgentsFromAgentPoolParams {
	return &GetAllAgentsFromAgentPoolParams{
		HTTPClient: client,
	}
}

/* GetAllAgentsFromAgentPoolParams contains all the parameters to send to the API endpoint
   for the get all agents from agent pool operation.

   Typically these are written to a http.Request.
*/
type GetAllAgentsFromAgentPoolParams struct {

	// AgentPoolLocator.
	//
	// Format: AgentPoolLocator
	AgentPoolLocator string

	// Fields.
	Fields *string

	// Locator.
	//
	// Format: AgentLocator
	Locator *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all agents from agent pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllAgentsFromAgentPoolParams) WithDefaults() *GetAllAgentsFromAgentPoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all agents from agent pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllAgentsFromAgentPoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) WithTimeout(timeout time.Duration) *GetAllAgentsFromAgentPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) WithContext(ctx context.Context) *GetAllAgentsFromAgentPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) WithHTTPClient(client *http.Client) *GetAllAgentsFromAgentPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentPoolLocator adds the agentPoolLocator to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) WithAgentPoolLocator(agentPoolLocator string) *GetAllAgentsFromAgentPoolParams {
	o.SetAgentPoolLocator(agentPoolLocator)
	return o
}

// SetAgentPoolLocator adds the agentPoolLocator to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) SetAgentPoolLocator(agentPoolLocator string) {
	o.AgentPoolLocator = agentPoolLocator
}

// WithFields adds the fields to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) WithFields(fields *string) *GetAllAgentsFromAgentPoolParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithLocator adds the locator to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) WithLocator(locator *string) *GetAllAgentsFromAgentPoolParams {
	o.SetLocator(locator)
	return o
}

// SetLocator adds the locator to the get all agents from agent pool params
func (o *GetAllAgentsFromAgentPoolParams) SetLocator(locator *string) {
	o.Locator = locator
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAgentsFromAgentPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agentPoolLocator
	if err := r.SetPathParam("agentPoolLocator", o.AgentPoolLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Locator != nil {

		// query param locator
		var qrLocator string

		if o.Locator != nil {
			qrLocator = *o.Locator
		}
		qLocator := qrLocator
		if qLocator != "" {

			if err := r.SetQueryParam("locator", qLocator); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
