// Code generated by go-swagger; DO NOT EDIT.

package mute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// GetMutedTestReader is a Reader for the GetMutedTest structure.
type GetMutedTestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMutedTestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMutedTestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMutedTestOK creates a GetMutedTestOK with default headers values
func NewGetMutedTestOK() *GetMutedTestOK {
	return &GetMutedTestOK{}
}

/* GetMutedTestOK describes a response with status code 200, with default header values.

successful operation
*/
type GetMutedTestOK struct {
	Payload *models.Mute
}

func (o *GetMutedTestOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/mutes/{muteLocator}][%d] getMutedTestOK  %+v", 200, o.Payload)
}
func (o *GetMutedTestOK) GetPayload() *models.Mute {
	return o.Payload
}

func (o *GetMutedTestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Mute)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
