// Code generated by go-swagger; DO NOT EDIT.

package change

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// GetChangeParentChangesReader is a Reader for the GetChangeParentChanges structure.
type GetChangeParentChangesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChangeParentChangesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetChangeParentChangesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetChangeParentChangesOK creates a GetChangeParentChangesOK with default headers values
func NewGetChangeParentChangesOK() *GetChangeParentChangesOK {
	return &GetChangeParentChangesOK{}
}

/* GetChangeParentChangesOK describes a response with status code 200, with default header values.

successful operation
*/
type GetChangeParentChangesOK struct {
	Payload *models.Changes
}

func (o *GetChangeParentChangesOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/changes/{changeLocator}/parentChanges][%d] getChangeParentChangesOK  %+v", 200, o.Payload)
}
func (o *GetChangeParentChangesOK) GetPayload() *models.Changes {
	return o.Payload
}

func (o *GetChangeParentChangesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Changes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
