// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewAddRoleToUserParams creates a new AddRoleToUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddRoleToUserParams() *AddRoleToUserParams {
	return &AddRoleToUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddRoleToUserParamsWithTimeout creates a new AddRoleToUserParams object
// with the ability to set a timeout on a request.
func NewAddRoleToUserParamsWithTimeout(timeout time.Duration) *AddRoleToUserParams {
	return &AddRoleToUserParams{
		timeout: timeout,
	}
}

// NewAddRoleToUserParamsWithContext creates a new AddRoleToUserParams object
// with the ability to set a context for a request.
func NewAddRoleToUserParamsWithContext(ctx context.Context) *AddRoleToUserParams {
	return &AddRoleToUserParams{
		Context: ctx,
	}
}

// NewAddRoleToUserParamsWithHTTPClient creates a new AddRoleToUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddRoleToUserParamsWithHTTPClient(client *http.Client) *AddRoleToUserParams {
	return &AddRoleToUserParams{
		HTTPClient: client,
	}
}

/* AddRoleToUserParams contains all the parameters to send to the API endpoint
   for the add role to user operation.

   Typically these are written to a http.Request.
*/
type AddRoleToUserParams struct {

	// Body.
	Body *models.Role

	// UserLocator.
	//
	// Format: UserLocator
	UserLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add role to user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddRoleToUserParams) WithDefaults() *AddRoleToUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add role to user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddRoleToUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add role to user params
func (o *AddRoleToUserParams) WithTimeout(timeout time.Duration) *AddRoleToUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add role to user params
func (o *AddRoleToUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add role to user params
func (o *AddRoleToUserParams) WithContext(ctx context.Context) *AddRoleToUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add role to user params
func (o *AddRoleToUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add role to user params
func (o *AddRoleToUserParams) WithHTTPClient(client *http.Client) *AddRoleToUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add role to user params
func (o *AddRoleToUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add role to user params
func (o *AddRoleToUserParams) WithBody(body *models.Role) *AddRoleToUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add role to user params
func (o *AddRoleToUserParams) SetBody(body *models.Role) {
	o.Body = body
}

// WithUserLocator adds the userLocator to the add role to user params
func (o *AddRoleToUserParams) WithUserLocator(userLocator string) *AddRoleToUserParams {
	o.SetUserLocator(userLocator)
	return o
}

// SetUserLocator adds the userLocator to the add role to user params
func (o *AddRoleToUserParams) SetUserLocator(userLocator string) {
	o.UserLocator = userLocator
}

// WriteToRequest writes these params to a swagger request
func (o *AddRoleToUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userLocator
	if err := r.SetPathParam("userLocator", o.UserLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
