// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteUserTokenReader is a Reader for the DeleteUserToken structure.
type DeleteUserTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteUserTokenDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteUserTokenDefault creates a DeleteUserTokenDefault with default headers values
func NewDeleteUserTokenDefault(code int) *DeleteUserTokenDefault {
	return &DeleteUserTokenDefault{
		_statusCode: code,
	}
}

/* DeleteUserTokenDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteUserTokenDefault struct {
	_statusCode int
}

// Code gets the status code for the delete user token default response
func (o *DeleteUserTokenDefault) Code() int {
	return o._statusCode
}

func (o *DeleteUserTokenDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/users/{userLocator}/tokens/{name}][%d] deleteUserToken default ", o._statusCode)
}

func (o *DeleteUserTokenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
