// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllUserGroupsParams creates a new GetAllUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllUserGroupsParams() *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllUserGroupsParamsWithTimeout creates a new GetAllUserGroupsParams object
// with the ability to set a timeout on a request.
func NewGetAllUserGroupsParamsWithTimeout(timeout time.Duration) *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		timeout: timeout,
	}
}

// NewGetAllUserGroupsParamsWithContext creates a new GetAllUserGroupsParams object
// with the ability to set a context for a request.
func NewGetAllUserGroupsParamsWithContext(ctx context.Context) *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		Context: ctx,
	}
}

// NewGetAllUserGroupsParamsWithHTTPClient creates a new GetAllUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllUserGroupsParamsWithHTTPClient(client *http.Client) *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		HTTPClient: client,
	}
}

/* GetAllUserGroupsParams contains all the parameters to send to the API endpoint
   for the get all user groups operation.

   Typically these are written to a http.Request.
*/
type GetAllUserGroupsParams struct {

	// Fields.
	Fields *string

	// UserLocator.
	//
	// Format: UserLocator
	UserLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllUserGroupsParams) WithDefaults() *GetAllUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllUserGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all user groups params
func (o *GetAllUserGroupsParams) WithTimeout(timeout time.Duration) *GetAllUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all user groups params
func (o *GetAllUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all user groups params
func (o *GetAllUserGroupsParams) WithContext(ctx context.Context) *GetAllUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all user groups params
func (o *GetAllUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all user groups params
func (o *GetAllUserGroupsParams) WithHTTPClient(client *http.Client) *GetAllUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all user groups params
func (o *GetAllUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get all user groups params
func (o *GetAllUserGroupsParams) WithFields(fields *string) *GetAllUserGroupsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get all user groups params
func (o *GetAllUserGroupsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserLocator adds the userLocator to the get all user groups params
func (o *GetAllUserGroupsParams) WithUserLocator(userLocator string) *GetAllUserGroupsParams {
	o.SetUserLocator(userLocator)
	return o
}

// SetUserLocator adds the userLocator to the get all user groups params
func (o *GetAllUserGroupsParams) SetUserLocator(userLocator string) {
	o.UserLocator = userLocator
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param userLocator
	if err := r.SetPathParam("userLocator", o.UserLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
