// Code generated by go-swagger; DO NOT EDIT.

package build_queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddTagsToBuildOfBuildQueueReader is a Reader for the AddTagsToBuildOfBuildQueue structure.
type AddTagsToBuildOfBuildQueueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddTagsToBuildOfBuildQueueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewAddTagsToBuildOfBuildQueueDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewAddTagsToBuildOfBuildQueueDefault creates a AddTagsToBuildOfBuildQueueDefault with default headers values
func NewAddTagsToBuildOfBuildQueueDefault(code int) *AddTagsToBuildOfBuildQueueDefault {
	return &AddTagsToBuildOfBuildQueueDefault{
		_statusCode: code,
	}
}

/* AddTagsToBuildOfBuildQueueDefault describes a response with status code -1, with default header values.

successful operation
*/
type AddTagsToBuildOfBuildQueueDefault struct {
	_statusCode int
}

// Code gets the status code for the add tags to build of build queue default response
func (o *AddTagsToBuildOfBuildQueueDefault) Code() int {
	return o._statusCode
}

func (o *AddTagsToBuildOfBuildQueueDefault) Error() string {
	return fmt.Sprintf("[POST /app/rest/buildQueue/{buildLocator}/tags][%d] addTagsToBuildOfBuildQueue default ", o._statusCode)
}

func (o *AddTagsToBuildOfBuildQueueDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
