// Code generated by go-swagger; DO NOT EDIT.

package build_queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAllQueuedBuildsReader is a Reader for the DeleteAllQueuedBuilds structure.
type DeleteAllQueuedBuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAllQueuedBuildsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteAllQueuedBuildsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteAllQueuedBuildsDefault creates a DeleteAllQueuedBuildsDefault with default headers values
func NewDeleteAllQueuedBuildsDefault(code int) *DeleteAllQueuedBuildsDefault {
	return &DeleteAllQueuedBuildsDefault{
		_statusCode: code,
	}
}

/* DeleteAllQueuedBuildsDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteAllQueuedBuildsDefault struct {
	_statusCode int
}

// Code gets the status code for the delete all queued builds default response
func (o *DeleteAllQueuedBuildsDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAllQueuedBuildsDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/buildQueue][%d] deleteAllQueuedBuilds default ", o._statusCode)
}

func (o *DeleteAllQueuedBuildsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
