// Code generated by go-swagger; DO NOT EDIT.

package build_queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAllQueuedBuildsParams creates a new DeleteAllQueuedBuildsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAllQueuedBuildsParams() *DeleteAllQueuedBuildsParams {
	return &DeleteAllQueuedBuildsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAllQueuedBuildsParamsWithTimeout creates a new DeleteAllQueuedBuildsParams object
// with the ability to set a timeout on a request.
func NewDeleteAllQueuedBuildsParamsWithTimeout(timeout time.Duration) *DeleteAllQueuedBuildsParams {
	return &DeleteAllQueuedBuildsParams{
		timeout: timeout,
	}
}

// NewDeleteAllQueuedBuildsParamsWithContext creates a new DeleteAllQueuedBuildsParams object
// with the ability to set a context for a request.
func NewDeleteAllQueuedBuildsParamsWithContext(ctx context.Context) *DeleteAllQueuedBuildsParams {
	return &DeleteAllQueuedBuildsParams{
		Context: ctx,
	}
}

// NewDeleteAllQueuedBuildsParamsWithHTTPClient creates a new DeleteAllQueuedBuildsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAllQueuedBuildsParamsWithHTTPClient(client *http.Client) *DeleteAllQueuedBuildsParams {
	return &DeleteAllQueuedBuildsParams{
		HTTPClient: client,
	}
}

/* DeleteAllQueuedBuildsParams contains all the parameters to send to the API endpoint
   for the delete all queued builds operation.

   Typically these are written to a http.Request.
*/
type DeleteAllQueuedBuildsParams struct {

	// Fields.
	Fields *string

	// Locator.
	//
	// Format: BuildQueueLocator
	Locator *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete all queued builds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAllQueuedBuildsParams) WithDefaults() *DeleteAllQueuedBuildsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete all queued builds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAllQueuedBuildsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) WithTimeout(timeout time.Duration) *DeleteAllQueuedBuildsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) WithContext(ctx context.Context) *DeleteAllQueuedBuildsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) WithHTTPClient(client *http.Client) *DeleteAllQueuedBuildsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) WithFields(fields *string) *DeleteAllQueuedBuildsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithLocator adds the locator to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) WithLocator(locator *string) *DeleteAllQueuedBuildsParams {
	o.SetLocator(locator)
	return o
}

// SetLocator adds the locator to the delete all queued builds params
func (o *DeleteAllQueuedBuildsParams) SetLocator(locator *string) {
	o.Locator = locator
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAllQueuedBuildsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Locator != nil {

		// query param locator
		var qrLocator string

		if o.Locator != nil {
			qrLocator = *o.Locator
		}
		qLocator := qrLocator
		if qLocator != "" {

			if err := r.SetQueryParam("locator", qLocator); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
