// Code generated by go-swagger; DO NOT EDIT.

package cloud_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllCloudInstancesParams creates a new GetAllCloudInstancesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllCloudInstancesParams() *GetAllCloudInstancesParams {
	return &GetAllCloudInstancesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllCloudInstancesParamsWithTimeout creates a new GetAllCloudInstancesParams object
// with the ability to set a timeout on a request.
func NewGetAllCloudInstancesParamsWithTimeout(timeout time.Duration) *GetAllCloudInstancesParams {
	return &GetAllCloudInstancesParams{
		timeout: timeout,
	}
}

// NewGetAllCloudInstancesParamsWithContext creates a new GetAllCloudInstancesParams object
// with the ability to set a context for a request.
func NewGetAllCloudInstancesParamsWithContext(ctx context.Context) *GetAllCloudInstancesParams {
	return &GetAllCloudInstancesParams{
		Context: ctx,
	}
}

// NewGetAllCloudInstancesParamsWithHTTPClient creates a new GetAllCloudInstancesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllCloudInstancesParamsWithHTTPClient(client *http.Client) *GetAllCloudInstancesParams {
	return &GetAllCloudInstancesParams{
		HTTPClient: client,
	}
}

/* GetAllCloudInstancesParams contains all the parameters to send to the API endpoint
   for the get all cloud instances operation.

   Typically these are written to a http.Request.
*/
type GetAllCloudInstancesParams struct {

	// Fields.
	Fields *string

	// Locator.
	Locator *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all cloud instances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCloudInstancesParams) WithDefaults() *GetAllCloudInstancesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all cloud instances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllCloudInstancesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all cloud instances params
func (o *GetAllCloudInstancesParams) WithTimeout(timeout time.Duration) *GetAllCloudInstancesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all cloud instances params
func (o *GetAllCloudInstancesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all cloud instances params
func (o *GetAllCloudInstancesParams) WithContext(ctx context.Context) *GetAllCloudInstancesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all cloud instances params
func (o *GetAllCloudInstancesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all cloud instances params
func (o *GetAllCloudInstancesParams) WithHTTPClient(client *http.Client) *GetAllCloudInstancesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all cloud instances params
func (o *GetAllCloudInstancesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get all cloud instances params
func (o *GetAllCloudInstancesParams) WithFields(fields *string) *GetAllCloudInstancesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get all cloud instances params
func (o *GetAllCloudInstancesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithLocator adds the locator to the get all cloud instances params
func (o *GetAllCloudInstancesParams) WithLocator(locator *string) *GetAllCloudInstancesParams {
	o.SetLocator(locator)
	return o
}

// SetLocator adds the locator to the get all cloud instances params
func (o *GetAllCloudInstancesParams) SetLocator(locator *string) {
	o.Locator = locator
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllCloudInstancesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Locator != nil {

		// query param locator
		var qrLocator string

		if o.Locator != nil {
			qrLocator = *o.Locator
		}
		qLocator := qrLocator
		if qLocator != "" {

			if err := r.SetQueryParam("locator", qLocator); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
