// Code generated by go-swagger; DO NOT EDIT.

package investigation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteInvestigationReader is a Reader for the DeleteInvestigation structure.
type DeleteInvestigationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInvestigationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteInvestigationDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteInvestigationDefault creates a DeleteInvestigationDefault with default headers values
func NewDeleteInvestigationDefault(code int) *DeleteInvestigationDefault {
	return &DeleteInvestigationDefault{
		_statusCode: code,
	}
}

/* DeleteInvestigationDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteInvestigationDefault struct {
	_statusCode int
}

// Code gets the status code for the delete investigation default response
func (o *DeleteInvestigationDefault) Code() int {
	return o._statusCode
}

func (o *DeleteInvestigationDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/investigations/{investigationLocator}][%d] deleteInvestigation default ", o._statusCode)
}

func (o *DeleteInvestigationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
