// Code generated by go-swagger; DO NOT EDIT.

package investigation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInvestigationParams creates a new GetInvestigationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInvestigationParams() *GetInvestigationParams {
	return &GetInvestigationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInvestigationParamsWithTimeout creates a new GetInvestigationParams object
// with the ability to set a timeout on a request.
func NewGetInvestigationParamsWithTimeout(timeout time.Duration) *GetInvestigationParams {
	return &GetInvestigationParams{
		timeout: timeout,
	}
}

// NewGetInvestigationParamsWithContext creates a new GetInvestigationParams object
// with the ability to set a context for a request.
func NewGetInvestigationParamsWithContext(ctx context.Context) *GetInvestigationParams {
	return &GetInvestigationParams{
		Context: ctx,
	}
}

// NewGetInvestigationParamsWithHTTPClient creates a new GetInvestigationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInvestigationParamsWithHTTPClient(client *http.Client) *GetInvestigationParams {
	return &GetInvestigationParams{
		HTTPClient: client,
	}
}

/* GetInvestigationParams contains all the parameters to send to the API endpoint
   for the get investigation operation.

   Typically these are written to a http.Request.
*/
type GetInvestigationParams struct {

	// Fields.
	Fields *string

	// InvestigationLocator.
	//
	// Format: InvestigationLocator
	InvestigationLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get investigation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInvestigationParams) WithDefaults() *GetInvestigationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get investigation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInvestigationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get investigation params
func (o *GetInvestigationParams) WithTimeout(timeout time.Duration) *GetInvestigationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get investigation params
func (o *GetInvestigationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get investigation params
func (o *GetInvestigationParams) WithContext(ctx context.Context) *GetInvestigationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get investigation params
func (o *GetInvestigationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get investigation params
func (o *GetInvestigationParams) WithHTTPClient(client *http.Client) *GetInvestigationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get investigation params
func (o *GetInvestigationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get investigation params
func (o *GetInvestigationParams) WithFields(fields *string) *GetInvestigationParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get investigation params
func (o *GetInvestigationParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithInvestigationLocator adds the investigationLocator to the get investigation params
func (o *GetInvestigationParams) WithInvestigationLocator(investigationLocator string) *GetInvestigationParams {
	o.SetInvestigationLocator(investigationLocator)
	return o
}

// SetInvestigationLocator adds the investigationLocator to the get investigation params
func (o *GetInvestigationParams) SetInvestigationLocator(investigationLocator string) {
	o.InvestigationLocator = investigationLocator
}

// WriteToRequest writes these params to a swagger request
func (o *GetInvestigationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param investigationLocator
	if err := r.SetPathParam("investigationLocator", o.InvestigationLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
