// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuditEventParams creates a new GetAuditEventParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuditEventParams() *GetAuditEventParams {
	return &GetAuditEventParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuditEventParamsWithTimeout creates a new GetAuditEventParams object
// with the ability to set a timeout on a request.
func NewGetAuditEventParamsWithTimeout(timeout time.Duration) *GetAuditEventParams {
	return &GetAuditEventParams{
		timeout: timeout,
	}
}

// NewGetAuditEventParamsWithContext creates a new GetAuditEventParams object
// with the ability to set a context for a request.
func NewGetAuditEventParamsWithContext(ctx context.Context) *GetAuditEventParams {
	return &GetAuditEventParams{
		Context: ctx,
	}
}

// NewGetAuditEventParamsWithHTTPClient creates a new GetAuditEventParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuditEventParamsWithHTTPClient(client *http.Client) *GetAuditEventParams {
	return &GetAuditEventParams{
		HTTPClient: client,
	}
}

/* GetAuditEventParams contains all the parameters to send to the API endpoint
   for the get audit event operation.

   Typically these are written to a http.Request.
*/
type GetAuditEventParams struct {

	// AuditEventLocator.
	//
	// Format: AuditLocator
	AuditEventLocator string

	// Fields.
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get audit event params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuditEventParams) WithDefaults() *GetAuditEventParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get audit event params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuditEventParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get audit event params
func (o *GetAuditEventParams) WithTimeout(timeout time.Duration) *GetAuditEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get audit event params
func (o *GetAuditEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get audit event params
func (o *GetAuditEventParams) WithContext(ctx context.Context) *GetAuditEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get audit event params
func (o *GetAuditEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get audit event params
func (o *GetAuditEventParams) WithHTTPClient(client *http.Client) *GetAuditEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get audit event params
func (o *GetAuditEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuditEventLocator adds the auditEventLocator to the get audit event params
func (o *GetAuditEventParams) WithAuditEventLocator(auditEventLocator string) *GetAuditEventParams {
	o.SetAuditEventLocator(auditEventLocator)
	return o
}

// SetAuditEventLocator adds the auditEventLocator to the get audit event params
func (o *GetAuditEventParams) SetAuditEventLocator(auditEventLocator string) {
	o.AuditEventLocator = auditEventLocator
}

// WithFields adds the fields to the get audit event params
func (o *GetAuditEventParams) WithFields(fields *string) *GetAuditEventParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get audit event params
func (o *GetAuditEventParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuditEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param auditEventLocator
	if err := r.SetPathParam("auditEventLocator", o.AuditEventLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
