// Code generated by go-swagger; DO NOT EDIT.

package vcs_root

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteVcsRootPropertyReader is a Reader for the DeleteVcsRootProperty structure.
type DeleteVcsRootPropertyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVcsRootPropertyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteVcsRootPropertyDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteVcsRootPropertyDefault creates a DeleteVcsRootPropertyDefault with default headers values
func NewDeleteVcsRootPropertyDefault(code int) *DeleteVcsRootPropertyDefault {
	return &DeleteVcsRootPropertyDefault{
		_statusCode: code,
	}
}

/* DeleteVcsRootPropertyDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteVcsRootPropertyDefault struct {
	_statusCode int
}

// Code gets the status code for the delete vcs root property default response
func (o *DeleteVcsRootPropertyDefault) Code() int {
	return o._statusCode
}

func (o *DeleteVcsRootPropertyDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/vcs-roots/{vcsRootLocator}/properties/{name}][%d] deleteVcsRootProperty default ", o._statusCode)
}

func (o *DeleteVcsRootPropertyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
