// Code generated by go-swagger; DO NOT EDIT.

package vcs_root

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllVcsRootsParams creates a new GetAllVcsRootsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllVcsRootsParams() *GetAllVcsRootsParams {
	return &GetAllVcsRootsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllVcsRootsParamsWithTimeout creates a new GetAllVcsRootsParams object
// with the ability to set a timeout on a request.
func NewGetAllVcsRootsParamsWithTimeout(timeout time.Duration) *GetAllVcsRootsParams {
	return &GetAllVcsRootsParams{
		timeout: timeout,
	}
}

// NewGetAllVcsRootsParamsWithContext creates a new GetAllVcsRootsParams object
// with the ability to set a context for a request.
func NewGetAllVcsRootsParamsWithContext(ctx context.Context) *GetAllVcsRootsParams {
	return &GetAllVcsRootsParams{
		Context: ctx,
	}
}

// NewGetAllVcsRootsParamsWithHTTPClient creates a new GetAllVcsRootsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllVcsRootsParamsWithHTTPClient(client *http.Client) *GetAllVcsRootsParams {
	return &GetAllVcsRootsParams{
		HTTPClient: client,
	}
}

/* GetAllVcsRootsParams contains all the parameters to send to the API endpoint
   for the get all vcs roots operation.

   Typically these are written to a http.Request.
*/
type GetAllVcsRootsParams struct {

	// Fields.
	Fields *string

	// Locator.
	//
	// Format: VcsRootLocator
	Locator *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all vcs roots params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllVcsRootsParams) WithDefaults() *GetAllVcsRootsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all vcs roots params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllVcsRootsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all vcs roots params
func (o *GetAllVcsRootsParams) WithTimeout(timeout time.Duration) *GetAllVcsRootsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all vcs roots params
func (o *GetAllVcsRootsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all vcs roots params
func (o *GetAllVcsRootsParams) WithContext(ctx context.Context) *GetAllVcsRootsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all vcs roots params
func (o *GetAllVcsRootsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all vcs roots params
func (o *GetAllVcsRootsParams) WithHTTPClient(client *http.Client) *GetAllVcsRootsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all vcs roots params
func (o *GetAllVcsRootsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get all vcs roots params
func (o *GetAllVcsRootsParams) WithFields(fields *string) *GetAllVcsRootsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get all vcs roots params
func (o *GetAllVcsRootsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithLocator adds the locator to the get all vcs roots params
func (o *GetAllVcsRootsParams) WithLocator(locator *string) *GetAllVcsRootsParams {
	o.SetLocator(locator)
	return o
}

// SetLocator adds the locator to the get all vcs roots params
func (o *GetAllVcsRootsParams) SetLocator(locator *string) {
	o.Locator = locator
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllVcsRootsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Locator != nil {

		// query param locator
		var qrLocator string

		if o.Locator != nil {
			qrLocator = *o.Locator
		}
		qLocator := qrLocator
		if qLocator != "" {

			if err := r.SetQueryParam("locator", qLocator); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
