// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupPropertiesParams creates a new GetGroupPropertiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupPropertiesParams() *GetGroupPropertiesParams {
	return &GetGroupPropertiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupPropertiesParamsWithTimeout creates a new GetGroupPropertiesParams object
// with the ability to set a timeout on a request.
func NewGetGroupPropertiesParamsWithTimeout(timeout time.Duration) *GetGroupPropertiesParams {
	return &GetGroupPropertiesParams{
		timeout: timeout,
	}
}

// NewGetGroupPropertiesParamsWithContext creates a new GetGroupPropertiesParams object
// with the ability to set a context for a request.
func NewGetGroupPropertiesParamsWithContext(ctx context.Context) *GetGroupPropertiesParams {
	return &GetGroupPropertiesParams{
		Context: ctx,
	}
}

// NewGetGroupPropertiesParamsWithHTTPClient creates a new GetGroupPropertiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupPropertiesParamsWithHTTPClient(client *http.Client) *GetGroupPropertiesParams {
	return &GetGroupPropertiesParams{
		HTTPClient: client,
	}
}

/* GetGroupPropertiesParams contains all the parameters to send to the API endpoint
   for the get group properties operation.

   Typically these are written to a http.Request.
*/
type GetGroupPropertiesParams struct {

	// Fields.
	Fields *string

	// GroupLocator.
	GroupLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group properties params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupPropertiesParams) WithDefaults() *GetGroupPropertiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group properties params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupPropertiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group properties params
func (o *GetGroupPropertiesParams) WithTimeout(timeout time.Duration) *GetGroupPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group properties params
func (o *GetGroupPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group properties params
func (o *GetGroupPropertiesParams) WithContext(ctx context.Context) *GetGroupPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group properties params
func (o *GetGroupPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group properties params
func (o *GetGroupPropertiesParams) WithHTTPClient(client *http.Client) *GetGroupPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group properties params
func (o *GetGroupPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get group properties params
func (o *GetGroupPropertiesParams) WithFields(fields *string) *GetGroupPropertiesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get group properties params
func (o *GetGroupPropertiesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithGroupLocator adds the groupLocator to the get group properties params
func (o *GetGroupPropertiesParams) WithGroupLocator(groupLocator string) *GetGroupPropertiesParams {
	o.SetGroupLocator(groupLocator)
	return o
}

// SetGroupLocator adds the groupLocator to the get group properties params
func (o *GetGroupPropertiesParams) SetGroupLocator(groupLocator string) {
	o.GroupLocator = groupLocator
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param groupLocator
	if err := r.SetPathParam("groupLocator", o.GroupLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
