// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// SetGroupRolesReader is a Reader for the SetGroupRoles structure.
type SetGroupRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetGroupRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetGroupRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetGroupRolesOK creates a SetGroupRolesOK with default headers values
func NewSetGroupRolesOK() *SetGroupRolesOK {
	return &SetGroupRolesOK{}
}

/* SetGroupRolesOK describes a response with status code 200, with default header values.

successful operation
*/
type SetGroupRolesOK struct {
	Payload *models.Roles
}

func (o *SetGroupRolesOK) Error() string {
	return fmt.Sprintf("[PUT /app/rest/userGroups/{groupLocator}/roles][%d] setGroupRolesOK  %+v", 200, o.Payload)
}
func (o *SetGroupRolesOK) GetPayload() *models.Roles {
	return o.Payload
}

func (o *SetGroupRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Roles)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
