// Code generated by go-swagger; DO NOT EDIT.

package vcs_root_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteVcsRootInstanceFieldReader is a Reader for the DeleteVcsRootInstanceField structure.
type DeleteVcsRootInstanceFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVcsRootInstanceFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteVcsRootInstanceFieldDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteVcsRootInstanceFieldDefault creates a DeleteVcsRootInstanceFieldDefault with default headers values
func NewDeleteVcsRootInstanceFieldDefault(code int) *DeleteVcsRootInstanceFieldDefault {
	return &DeleteVcsRootInstanceFieldDefault{
		_statusCode: code,
	}
}

/* DeleteVcsRootInstanceFieldDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteVcsRootInstanceFieldDefault struct {
	_statusCode int
}

// Code gets the status code for the delete vcs root instance field default response
func (o *DeleteVcsRootInstanceFieldDefault) Code() int {
	return o._statusCode
}

func (o *DeleteVcsRootInstanceFieldDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/vcs-root-instances/{vcsRootInstanceLocator}/{field}][%d] deleteVcsRootInstanceField default ", o._statusCode)
}

func (o *DeleteVcsRootInstanceFieldDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
