// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthorizedInfoParams creates a new GetAuthorizedInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthorizedInfoParams() *GetAuthorizedInfoParams {
	return &GetAuthorizedInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthorizedInfoParamsWithTimeout creates a new GetAuthorizedInfoParams object
// with the ability to set a timeout on a request.
func NewGetAuthorizedInfoParamsWithTimeout(timeout time.Duration) *GetAuthorizedInfoParams {
	return &GetAuthorizedInfoParams{
		timeout: timeout,
	}
}

// NewGetAuthorizedInfoParamsWithContext creates a new GetAuthorizedInfoParams object
// with the ability to set a context for a request.
func NewGetAuthorizedInfoParamsWithContext(ctx context.Context) *GetAuthorizedInfoParams {
	return &GetAuthorizedInfoParams{
		Context: ctx,
	}
}

// NewGetAuthorizedInfoParamsWithHTTPClient creates a new GetAuthorizedInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthorizedInfoParamsWithHTTPClient(client *http.Client) *GetAuthorizedInfoParams {
	return &GetAuthorizedInfoParams{
		HTTPClient: client,
	}
}

/* GetAuthorizedInfoParams contains all the parameters to send to the API endpoint
   for the get authorized info operation.

   Typically these are written to a http.Request.
*/
type GetAuthorizedInfoParams struct {

	// AgentLocator.
	//
	// Format: AgentLocator
	AgentLocator string

	// Fields.
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get authorized info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthorizedInfoParams) WithDefaults() *GetAuthorizedInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get authorized info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthorizedInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get authorized info params
func (o *GetAuthorizedInfoParams) WithTimeout(timeout time.Duration) *GetAuthorizedInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get authorized info params
func (o *GetAuthorizedInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get authorized info params
func (o *GetAuthorizedInfoParams) WithContext(ctx context.Context) *GetAuthorizedInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get authorized info params
func (o *GetAuthorizedInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get authorized info params
func (o *GetAuthorizedInfoParams) WithHTTPClient(client *http.Client) *GetAuthorizedInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get authorized info params
func (o *GetAuthorizedInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentLocator adds the agentLocator to the get authorized info params
func (o *GetAuthorizedInfoParams) WithAgentLocator(agentLocator string) *GetAuthorizedInfoParams {
	o.SetAgentLocator(agentLocator)
	return o
}

// SetAgentLocator adds the agentLocator to the get authorized info params
func (o *GetAuthorizedInfoParams) SetAgentLocator(agentLocator string) {
	o.AgentLocator = agentLocator
}

// WithFields adds the fields to the get authorized info params
func (o *GetAuthorizedInfoParams) WithFields(fields *string) *GetAuthorizedInfoParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get authorized info params
func (o *GetAuthorizedInfoParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthorizedInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agentLocator
	if err := r.SetPathParam("agentLocator", o.AgentLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
