// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewSetBuildConfigurationRunPolicyParams creates a new SetBuildConfigurationRunPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetBuildConfigurationRunPolicyParams() *SetBuildConfigurationRunPolicyParams {
	return &SetBuildConfigurationRunPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetBuildConfigurationRunPolicyParamsWithTimeout creates a new SetBuildConfigurationRunPolicyParams object
// with the ability to set a timeout on a request.
func NewSetBuildConfigurationRunPolicyParamsWithTimeout(timeout time.Duration) *SetBuildConfigurationRunPolicyParams {
	return &SetBuildConfigurationRunPolicyParams{
		timeout: timeout,
	}
}

// NewSetBuildConfigurationRunPolicyParamsWithContext creates a new SetBuildConfigurationRunPolicyParams object
// with the ability to set a context for a request.
func NewSetBuildConfigurationRunPolicyParamsWithContext(ctx context.Context) *SetBuildConfigurationRunPolicyParams {
	return &SetBuildConfigurationRunPolicyParams{
		Context: ctx,
	}
}

// NewSetBuildConfigurationRunPolicyParamsWithHTTPClient creates a new SetBuildConfigurationRunPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetBuildConfigurationRunPolicyParamsWithHTTPClient(client *http.Client) *SetBuildConfigurationRunPolicyParams {
	return &SetBuildConfigurationRunPolicyParams{
		HTTPClient: client,
	}
}

/* SetBuildConfigurationRunPolicyParams contains all the parameters to send to the API endpoint
   for the set build configuration run policy operation.

   Typically these are written to a http.Request.
*/
type SetBuildConfigurationRunPolicyParams struct {

	// AgentLocator.
	//
	// Format: AgentLocator
	AgentLocator string

	// Body.
	Body *models.CompatibilityPolicy

	// Fields.
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set build configuration run policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetBuildConfigurationRunPolicyParams) WithDefaults() *SetBuildConfigurationRunPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set build configuration run policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetBuildConfigurationRunPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) WithTimeout(timeout time.Duration) *SetBuildConfigurationRunPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) WithContext(ctx context.Context) *SetBuildConfigurationRunPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) WithHTTPClient(client *http.Client) *SetBuildConfigurationRunPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentLocator adds the agentLocator to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) WithAgentLocator(agentLocator string) *SetBuildConfigurationRunPolicyParams {
	o.SetAgentLocator(agentLocator)
	return o
}

// SetAgentLocator adds the agentLocator to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) SetAgentLocator(agentLocator string) {
	o.AgentLocator = agentLocator
}

// WithBody adds the body to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) WithBody(body *models.CompatibilityPolicy) *SetBuildConfigurationRunPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) SetBody(body *models.CompatibilityPolicy) {
	o.Body = body
}

// WithFields adds the fields to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) WithFields(fields *string) *SetBuildConfigurationRunPolicyParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the set build configuration run policy params
func (o *SetBuildConfigurationRunPolicyParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *SetBuildConfigurationRunPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agentLocator
	if err := r.SetPathParam("agentLocator", o.AgentLocator); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
