// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewAddTemplateParams creates a new AddTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddTemplateParams() *AddTemplateParams {
	return &AddTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddTemplateParamsWithTimeout creates a new AddTemplateParams object
// with the ability to set a timeout on a request.
func NewAddTemplateParamsWithTimeout(timeout time.Duration) *AddTemplateParams {
	return &AddTemplateParams{
		timeout: timeout,
	}
}

// NewAddTemplateParamsWithContext creates a new AddTemplateParams object
// with the ability to set a context for a request.
func NewAddTemplateParamsWithContext(ctx context.Context) *AddTemplateParams {
	return &AddTemplateParams{
		Context: ctx,
	}
}

// NewAddTemplateParamsWithHTTPClient creates a new AddTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddTemplateParamsWithHTTPClient(client *http.Client) *AddTemplateParams {
	return &AddTemplateParams{
		HTTPClient: client,
	}
}

/* AddTemplateParams contains all the parameters to send to the API endpoint
   for the add template operation.

   Typically these are written to a http.Request.
*/
type AddTemplateParams struct {

	// Body.
	Body *models.NewBuildTypeDescription

	// Fields.
	Fields *string

	// ProjectLocator.
	//
	// Format: ProjectLocator
	ProjectLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddTemplateParams) WithDefaults() *AddTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add template params
func (o *AddTemplateParams) WithTimeout(timeout time.Duration) *AddTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add template params
func (o *AddTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add template params
func (o *AddTemplateParams) WithContext(ctx context.Context) *AddTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add template params
func (o *AddTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add template params
func (o *AddTemplateParams) WithHTTPClient(client *http.Client) *AddTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add template params
func (o *AddTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add template params
func (o *AddTemplateParams) WithBody(body *models.NewBuildTypeDescription) *AddTemplateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add template params
func (o *AddTemplateParams) SetBody(body *models.NewBuildTypeDescription) {
	o.Body = body
}

// WithFields adds the fields to the add template params
func (o *AddTemplateParams) WithFields(fields *string) *AddTemplateParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the add template params
func (o *AddTemplateParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithProjectLocator adds the projectLocator to the add template params
func (o *AddTemplateParams) WithProjectLocator(projectLocator string) *AddTemplateParams {
	o.SetProjectLocator(projectLocator)
	return o
}

// SetProjectLocator adds the projectLocator to the add template params
func (o *AddTemplateParams) SetProjectLocator(projectLocator string) {
	o.ProjectLocator = projectLocator
}

// WriteToRequest writes these params to a swagger request
func (o *AddTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param projectLocator
	if err := r.SetPathParam("projectLocator", o.ProjectLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
