// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddSecureTokenParams creates a new AddSecureTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddSecureTokenParams() *AddSecureTokenParams {
	return &AddSecureTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddSecureTokenParamsWithTimeout creates a new AddSecureTokenParams object
// with the ability to set a timeout on a request.
func NewAddSecureTokenParamsWithTimeout(timeout time.Duration) *AddSecureTokenParams {
	return &AddSecureTokenParams{
		timeout: timeout,
	}
}

// NewAddSecureTokenParamsWithContext creates a new AddSecureTokenParams object
// with the ability to set a context for a request.
func NewAddSecureTokenParamsWithContext(ctx context.Context) *AddSecureTokenParams {
	return &AddSecureTokenParams{
		Context: ctx,
	}
}

// NewAddSecureTokenParamsWithHTTPClient creates a new AddSecureTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddSecureTokenParamsWithHTTPClient(client *http.Client) *AddSecureTokenParams {
	return &AddSecureTokenParams{
		HTTPClient: client,
	}
}

/* AddSecureTokenParams contains all the parameters to send to the API endpoint
   for the add secure token operation.

   Typically these are written to a http.Request.
*/
type AddSecureTokenParams struct {

	// Body.
	Body string

	// ProjectLocator.
	//
	// Format: ProjectLocator
	ProjectLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add secure token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSecureTokenParams) WithDefaults() *AddSecureTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add secure token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSecureTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add secure token params
func (o *AddSecureTokenParams) WithTimeout(timeout time.Duration) *AddSecureTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add secure token params
func (o *AddSecureTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add secure token params
func (o *AddSecureTokenParams) WithContext(ctx context.Context) *AddSecureTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add secure token params
func (o *AddSecureTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add secure token params
func (o *AddSecureTokenParams) WithHTTPClient(client *http.Client) *AddSecureTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add secure token params
func (o *AddSecureTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add secure token params
func (o *AddSecureTokenParams) WithBody(body string) *AddSecureTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add secure token params
func (o *AddSecureTokenParams) SetBody(body string) {
	o.Body = body
}

// WithProjectLocator adds the projectLocator to the add secure token params
func (o *AddSecureTokenParams) WithProjectLocator(projectLocator string) *AddSecureTokenParams {
	o.SetProjectLocator(projectLocator)
	return o
}

// SetProjectLocator adds the projectLocator to the add secure token params
func (o *AddSecureTokenParams) SetProjectLocator(projectLocator string) {
	o.ProjectLocator = projectLocator
}

// WriteToRequest writes these params to a swagger request
func (o *AddSecureTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectLocator
	if err := r.SetPathParam("projectLocator", o.ProjectLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
