// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteBuildParameterReader is a Reader for the DeleteBuildParameter structure.
type DeleteBuildParameterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBuildParameterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteBuildParameterDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteBuildParameterDefault creates a DeleteBuildParameterDefault with default headers values
func NewDeleteBuildParameterDefault(code int) *DeleteBuildParameterDefault {
	return &DeleteBuildParameterDefault{
		_statusCode: code,
	}
}

/* DeleteBuildParameterDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteBuildParameterDefault struct {
	_statusCode int
}

// Code gets the status code for the delete build parameter default response
func (o *DeleteBuildParameterDefault) Code() int {
	return o._statusCode
}

func (o *DeleteBuildParameterDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/projects/{projectLocator}/parameters/{name}][%d] deleteBuildParameter default ", o._statusCode)
}

func (o *DeleteBuildParameterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
