// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFeatureParams creates a new GetFeatureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFeatureParams() *GetFeatureParams {
	return &GetFeatureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeatureParamsWithTimeout creates a new GetFeatureParams object
// with the ability to set a timeout on a request.
func NewGetFeatureParamsWithTimeout(timeout time.Duration) *GetFeatureParams {
	return &GetFeatureParams{
		timeout: timeout,
	}
}

// NewGetFeatureParamsWithContext creates a new GetFeatureParams object
// with the ability to set a context for a request.
func NewGetFeatureParamsWithContext(ctx context.Context) *GetFeatureParams {
	return &GetFeatureParams{
		Context: ctx,
	}
}

// NewGetFeatureParamsWithHTTPClient creates a new GetFeatureParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFeatureParamsWithHTTPClient(client *http.Client) *GetFeatureParams {
	return &GetFeatureParams{
		HTTPClient: client,
	}
}

/* GetFeatureParams contains all the parameters to send to the API endpoint
   for the get feature operation.

   Typically these are written to a http.Request.
*/
type GetFeatureParams struct {

	// FeatureLocator.
	FeatureLocator string

	// Fields.
	Fields *string

	// ProjectLocator.
	//
	// Format: ProjectLocator
	ProjectLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get feature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFeatureParams) WithDefaults() *GetFeatureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get feature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFeatureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get feature params
func (o *GetFeatureParams) WithTimeout(timeout time.Duration) *GetFeatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feature params
func (o *GetFeatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feature params
func (o *GetFeatureParams) WithContext(ctx context.Context) *GetFeatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feature params
func (o *GetFeatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feature params
func (o *GetFeatureParams) WithHTTPClient(client *http.Client) *GetFeatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feature params
func (o *GetFeatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFeatureLocator adds the featureLocator to the get feature params
func (o *GetFeatureParams) WithFeatureLocator(featureLocator string) *GetFeatureParams {
	o.SetFeatureLocator(featureLocator)
	return o
}

// SetFeatureLocator adds the featureLocator to the get feature params
func (o *GetFeatureParams) SetFeatureLocator(featureLocator string) {
	o.FeatureLocator = featureLocator
}

// WithFields adds the fields to the get feature params
func (o *GetFeatureParams) WithFields(fields *string) *GetFeatureParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get feature params
func (o *GetFeatureParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithProjectLocator adds the projectLocator to the get feature params
func (o *GetFeatureParams) WithProjectLocator(projectLocator string) *GetFeatureParams {
	o.SetProjectLocator(projectLocator)
	return o
}

// SetProjectLocator adds the projectLocator to the get feature params
func (o *GetFeatureParams) SetProjectLocator(projectLocator string) {
	o.ProjectLocator = projectLocator
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param featureLocator
	if err := r.SetPathParam("featureLocator", o.FeatureLocator); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param projectLocator
	if err := r.SetPathParam("projectLocator", o.ProjectLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
