// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBuildParameterParams creates a new GetBuildParameterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBuildParameterParams() *GetBuildParameterParams {
	return &GetBuildParameterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBuildParameterParamsWithTimeout creates a new GetBuildParameterParams object
// with the ability to set a timeout on a request.
func NewGetBuildParameterParamsWithTimeout(timeout time.Duration) *GetBuildParameterParams {
	return &GetBuildParameterParams{
		timeout: timeout,
	}
}

// NewGetBuildParameterParamsWithContext creates a new GetBuildParameterParams object
// with the ability to set a context for a request.
func NewGetBuildParameterParamsWithContext(ctx context.Context) *GetBuildParameterParams {
	return &GetBuildParameterParams{
		Context: ctx,
	}
}

// NewGetBuildParameterParamsWithHTTPClient creates a new GetBuildParameterParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBuildParameterParamsWithHTTPClient(client *http.Client) *GetBuildParameterParams {
	return &GetBuildParameterParams{
		HTTPClient: client,
	}
}

/* GetBuildParameterParams contains all the parameters to send to the API endpoint
   for the get build parameter operation.

   Typically these are written to a http.Request.
*/
type GetBuildParameterParams struct {

	// Fields.
	Fields *string

	// Name.
	Name string

	// ProjectLocator.
	//
	// Format: ProjectLocator
	ProjectLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get build parameter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildParameterParams) WithDefaults() *GetBuildParameterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get build parameter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildParameterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get build parameter params
func (o *GetBuildParameterParams) WithTimeout(timeout time.Duration) *GetBuildParameterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get build parameter params
func (o *GetBuildParameterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get build parameter params
func (o *GetBuildParameterParams) WithContext(ctx context.Context) *GetBuildParameterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get build parameter params
func (o *GetBuildParameterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get build parameter params
func (o *GetBuildParameterParams) WithHTTPClient(client *http.Client) *GetBuildParameterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get build parameter params
func (o *GetBuildParameterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get build parameter params
func (o *GetBuildParameterParams) WithFields(fields *string) *GetBuildParameterParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get build parameter params
func (o *GetBuildParameterParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithName adds the name to the get build parameter params
func (o *GetBuildParameterParams) WithName(name string) *GetBuildParameterParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get build parameter params
func (o *GetBuildParameterParams) SetName(name string) {
	o.Name = name
}

// WithProjectLocator adds the projectLocator to the get build parameter params
func (o *GetBuildParameterParams) WithProjectLocator(projectLocator string) *GetBuildParameterParams {
	o.SetProjectLocator(projectLocator)
	return o
}

// SetProjectLocator adds the projectLocator to the get build parameter params
func (o *GetBuildParameterParams) SetProjectLocator(projectLocator string) {
	o.ProjectLocator = projectLocator
}

// WriteToRequest writes these params to a swagger request
func (o *GetBuildParameterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param projectLocator
	if err := r.SetPathParam("projectLocator", o.ProjectLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
