// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RemoveProjectFromAgentPoolReader is a Reader for the RemoveProjectFromAgentPool structure.
type RemoveProjectFromAgentPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveProjectFromAgentPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewRemoveProjectFromAgentPoolDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewRemoveProjectFromAgentPoolDefault creates a RemoveProjectFromAgentPoolDefault with default headers values
func NewRemoveProjectFromAgentPoolDefault(code int) *RemoveProjectFromAgentPoolDefault {
	return &RemoveProjectFromAgentPoolDefault{
		_statusCode: code,
	}
}

/* RemoveProjectFromAgentPoolDefault describes a response with status code -1, with default header values.

successful operation
*/
type RemoveProjectFromAgentPoolDefault struct {
	_statusCode int
}

// Code gets the status code for the remove project from agent pool default response
func (o *RemoveProjectFromAgentPoolDefault) Code() int {
	return o._statusCode
}

func (o *RemoveProjectFromAgentPoolDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/projects/{projectLocator}/agentPools/{agentPoolLocator}][%d] removeProjectFromAgentPool default ", o._statusCode)
}

func (o *RemoveProjectFromAgentPoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
