// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rishabh96b/teamcity-client/models"
)

// NewSetDefaultTemplateParams creates a new SetDefaultTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetDefaultTemplateParams() *SetDefaultTemplateParams {
	return &SetDefaultTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetDefaultTemplateParamsWithTimeout creates a new SetDefaultTemplateParams object
// with the ability to set a timeout on a request.
func NewSetDefaultTemplateParamsWithTimeout(timeout time.Duration) *SetDefaultTemplateParams {
	return &SetDefaultTemplateParams{
		timeout: timeout,
	}
}

// NewSetDefaultTemplateParamsWithContext creates a new SetDefaultTemplateParams object
// with the ability to set a context for a request.
func NewSetDefaultTemplateParamsWithContext(ctx context.Context) *SetDefaultTemplateParams {
	return &SetDefaultTemplateParams{
		Context: ctx,
	}
}

// NewSetDefaultTemplateParamsWithHTTPClient creates a new SetDefaultTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetDefaultTemplateParamsWithHTTPClient(client *http.Client) *SetDefaultTemplateParams {
	return &SetDefaultTemplateParams{
		HTTPClient: client,
	}
}

/* SetDefaultTemplateParams contains all the parameters to send to the API endpoint
   for the set default template operation.

   Typically these are written to a http.Request.
*/
type SetDefaultTemplateParams struct {

	// Body.
	Body *models.BuildType

	// Fields.
	Fields *string

	// ProjectLocator.
	//
	// Format: ProjectLocator
	ProjectLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set default template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetDefaultTemplateParams) WithDefaults() *SetDefaultTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set default template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetDefaultTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set default template params
func (o *SetDefaultTemplateParams) WithTimeout(timeout time.Duration) *SetDefaultTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set default template params
func (o *SetDefaultTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set default template params
func (o *SetDefaultTemplateParams) WithContext(ctx context.Context) *SetDefaultTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set default template params
func (o *SetDefaultTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set default template params
func (o *SetDefaultTemplateParams) WithHTTPClient(client *http.Client) *SetDefaultTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set default template params
func (o *SetDefaultTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set default template params
func (o *SetDefaultTemplateParams) WithBody(body *models.BuildType) *SetDefaultTemplateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set default template params
func (o *SetDefaultTemplateParams) SetBody(body *models.BuildType) {
	o.Body = body
}

// WithFields adds the fields to the set default template params
func (o *SetDefaultTemplateParams) WithFields(fields *string) *SetDefaultTemplateParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the set default template params
func (o *SetDefaultTemplateParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithProjectLocator adds the projectLocator to the set default template params
func (o *SetDefaultTemplateParams) WithProjectLocator(projectLocator string) *SetDefaultTemplateParams {
	o.SetProjectLocator(projectLocator)
	return o
}

// SetProjectLocator adds the projectLocator to the set default template params
func (o *SetDefaultTemplateParams) SetProjectLocator(projectLocator string) {
	o.ProjectLocator = projectLocator
}

// WriteToRequest writes these params to a swagger request
func (o *SetDefaultTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param projectLocator
	if err := r.SetPathParam("projectLocator", o.ProjectLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
