// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Customizations Represents build customizations (artifact dependency overrides, custom parameters or changesets).
//
// swagger:model customizations
type Customizations struct {

	// artifact dependencies
	ArtifactDependencies map[string]string `json:"artifactDependencies,omitempty"`

	// changes
	Changes map[string]string `json:"changes,omitempty"`

	// parameters
	Parameters map[string]string `json:"parameters,omitempty"`
}

// Validate validates this customizations
func (m *Customizations) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this customizations based on context it is used
func (m *Customizations) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Customizations) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Customizations) UnmarshalBinary(b []byte) error {
	var res Customizations
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
