// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricValues Represents a list of MetricValue entities.
//
// swagger:model metricValues
type MetricValues struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count,attr,omitempty"`

	// metric value
	MetricValue []*MetricValue `json:"metricValue"`
}

// Validate validates this metric values
func (m *MetricValues) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetricValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricValues) validateMetricValue(formats strfmt.Registry) error {
	if swag.IsZero(m.MetricValue) { // not required
		return nil
	}

	for i := 0; i < len(m.MetricValue); i++ {
		if swag.IsZero(m.MetricValue[i]) { // not required
			continue
		}

		if m.MetricValue[i] != nil {
			if err := m.MetricValue[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metricValue" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("metricValue" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this metric values based on the context it is used
func (m *MetricValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetricValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricValues) contextValidateMetricValue(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MetricValue); i++ {

		if m.MetricValue[i] != nil {
			if err := m.MetricValue[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metricValue" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("metricValue" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetricValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricValues) UnmarshalBinary(b []byte) error {
	var res MetricValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
