// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PermissionAssignments Represents a list of PermissionAssignment entities.
//
// swagger:model permissionAssignments
type PermissionAssignments struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count,attr,omitempty"`

	// permission assignment
	PermissionAssignment []*PermissionAssignment `json:"permissionAssignment"`
}

// Validate validates this permission assignments
func (m *PermissionAssignments) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissionAssignment(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionAssignments) validatePermissionAssignment(formats strfmt.Registry) error {
	if swag.IsZero(m.PermissionAssignment) { // not required
		return nil
	}

	for i := 0; i < len(m.PermissionAssignment); i++ {
		if swag.IsZero(m.PermissionAssignment[i]) { // not required
			continue
		}

		if m.PermissionAssignment[i] != nil {
			if err := m.PermissionAssignment[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("permissionAssignment" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("permissionAssignment" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this permission assignments based on the context it is used
func (m *PermissionAssignments) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePermissionAssignment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionAssignments) contextValidatePermissionAssignment(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PermissionAssignment); i++ {

		if m.PermissionAssignment[i] != nil {
			if err := m.PermissionAssignment[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("permissionAssignment" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("permissionAssignment" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PermissionAssignments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PermissionAssignments) UnmarshalBinary(b []byte) error {
	var res PermissionAssignments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
