// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PermissionRestrictions Represents a list of PermissionRestriction entities.
//
// swagger:model permissionRestrictions
type PermissionRestrictions struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count,attr,omitempty"`

	// permission restriction
	PermissionRestriction []*PermissionRestriction `json:"permissionRestriction"`
}

// Validate validates this permission restrictions
func (m *PermissionRestrictions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissionRestriction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionRestrictions) validatePermissionRestriction(formats strfmt.Registry) error {
	if swag.IsZero(m.PermissionRestriction) { // not required
		return nil
	}

	for i := 0; i < len(m.PermissionRestriction); i++ {
		if swag.IsZero(m.PermissionRestriction[i]) { // not required
			continue
		}

		if m.PermissionRestriction[i] != nil {
			if err := m.PermissionRestriction[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("permissionRestriction" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("permissionRestriction" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this permission restrictions based on the context it is used
func (m *PermissionRestrictions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePermissionRestriction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PermissionRestrictions) contextValidatePermissionRestriction(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PermissionRestriction); i++ {

		if m.PermissionRestriction[i] != nil {
			if err := m.PermissionRestriction[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("permissionRestriction" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("permissionRestriction" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PermissionRestrictions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PermissionRestrictions) UnmarshalBinary(b []byte) error {
	var res PermissionRestrictions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
