// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProblemTarget Represents an investigation target.
//
// swagger:model ProblemTarget
type ProblemTarget struct {

	// any problem
	AnyProblem bool `json:"anyProblem,omitempty" xml:"anyProblem,attr,omitempty"`

	// problems
	Problems *Problems `json:"problems,omitempty"`

	// tests
	Tests *Tests `json:"tests,omitempty"`
}

// Validate validates this problem target
func (m *ProblemTarget) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProblems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProblemTarget) validateProblems(formats strfmt.Registry) error {
	if swag.IsZero(m.Problems) { // not required
		return nil
	}

	if m.Problems != nil {
		if err := m.Problems.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("problems")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("problems")
			}
			return err
		}
	}

	return nil
}

func (m *ProblemTarget) validateTests(formats strfmt.Registry) error {
	if swag.IsZero(m.Tests) { // not required
		return nil
	}

	if m.Tests != nil {
		if err := m.Tests.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tests")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tests")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this problem target based on the context it is used
func (m *ProblemTarget) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProblems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProblemTarget) contextValidateProblems(ctx context.Context, formats strfmt.Registry) error {

	if m.Problems != nil {
		if err := m.Problems.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("problems")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("problems")
			}
			return err
		}
	}

	return nil
}

func (m *ProblemTarget) contextValidateTests(ctx context.Context, formats strfmt.Registry) error {

	if m.Tests != nil {
		if err := m.Tests.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tests")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tests")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProblemTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProblemTarget) UnmarshalBinary(b []byte) error {
	var res ProblemTarget
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
