// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProblemLocator Represents a locator string for filtering Problem entities.
//
// swagger:model ProblemLocator
type ProblemLocator struct {

	// Project (direct or indirect parent) locator.
	AffectedProject string `json:"affectedProject,omitempty"`

	// Build locator.
	Build string `json:"build,omitempty"`

	// For paginated calls, how many entities to return per page.
	Count int32 `json:"count,omitempty"`

	// Is currently failing.
	CurrentlyFailing bool `json:"currentlyFailing,omitempty"`

	// Is currently investigated.
	CurrentlyInvestigated bool `json:"currentlyInvestigated,omitempty"`

	// Is currently muted.
	CurrentlyMuted bool `json:"currentlyMuted,omitempty"`

	// Entity ID.
	ID int32 `json:"id,omitempty"`

	// identity
	Identity string `json:"identity,omitempty"`

	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`

	// Limit processing to the latest `<lookupLimit>` entities.
	LookupLimit int32 `json:"lookupLimit,omitempty"`

	// For paginated calls, from which entity to start rendering the page.
	Start int32 `json:"start,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this problem locator
func (m *ProblemLocator) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this problem locator based on context it is used
func (m *ProblemLocator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProblemLocator) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProblemLocator) UnmarshalBinary(b []byte) error {
	var res ProblemLocator
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
