// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SnapshotDependencies Represents a list of SnapshotDependency entities.
//
// swagger:model snapshot-dependencies
type SnapshotDependencies struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count,attr,omitempty"`

	// snapshot dependency
	SnapshotDependency []*SnapshotDependency `json:"snapshot-dependency"`
}

// Validate validates this snapshot dependencies
func (m *SnapshotDependencies) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSnapshotDependency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SnapshotDependencies) validateSnapshotDependency(formats strfmt.Registry) error {
	if swag.IsZero(m.SnapshotDependency) { // not required
		return nil
	}

	for i := 0; i < len(m.SnapshotDependency); i++ {
		if swag.IsZero(m.SnapshotDependency[i]) { // not required
			continue
		}

		if m.SnapshotDependency[i] != nil {
			if err := m.SnapshotDependency[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("snapshot-dependency" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("snapshot-dependency" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this snapshot dependencies based on the context it is used
func (m *SnapshotDependencies) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSnapshotDependency(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SnapshotDependencies) contextValidateSnapshotDependency(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SnapshotDependency); i++ {

		if m.SnapshotDependency[i] != nil {
			if err := m.SnapshotDependency[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("snapshot-dependency" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("snapshot-dependency" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SnapshotDependencies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnapshotDependencies) UnmarshalBinary(b []byte) error {
	var res SnapshotDependencies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
