// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TestCounters Represents a test results counter (how many times this test was successful/failed/muted/ignored).
//
// swagger:model testCounters
type TestCounters struct {

	// all
	All int32 `json:"all,omitempty" xml:"all,attr,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty" xml:"duration,attr,omitempty"`

	// failed
	Failed int32 `json:"failed,omitempty" xml:"failed,attr,omitempty"`

	// ignored
	Ignored int32 `json:"ignored,omitempty" xml:"ignored,attr,omitempty"`

	// muted
	Muted int32 `json:"muted,omitempty" xml:"muted,attr,omitempty"`

	// new failed
	NewFailed int32 `json:"newFailed,omitempty" xml:"newFailed,attr,omitempty"`

	// success
	Success int32 `json:"success,omitempty" xml:"success,attr,omitempty"`
}

// Validate validates this test counters
func (m *TestCounters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this test counters based on context it is used
func (m *TestCounters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TestCounters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestCounters) UnmarshalBinary(b []byte) error {
	var res TestCounters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
